id: IE53527A1
source: https://www.lotsawahouse.org
source_file: null
initial_creation_type: input
imported: '2022-05-30T18:21:24.677421'
last_modified: '2022-05-30T18:21:24.677432'
parser: null
source_metadata:
  title: Amdo Geshe Jampal Rolwé Lodrö
  language: en
  description: Texts by and about Amdo Geshe Jampal Rolwé Lodrö (a mdo dge bshes 'jam
    dpal rol ba'i blo gros, 1888–1936), a prominent Gelugpa author who composed a
    treatise on Dzogchen and appealed against sectarianism.
  volume:
    f4938:
      title: 'The Jewelled Garland: An Aspiration for the Spread of the Teachings
        of the Omniscient Father and Son, Masters of the Teachings of the Ancient
        Translations'
      base_file: f4938.txt
      order: 1
      parent: Aspiration Prayers
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
